language/ru.xml
plugins/bat/lang/ru.xml
plugins/dmraid/lang/ru.xml
plugins/ipmiinfo/lang/ru.xml
plugins/updatenotifier/lang/ru.xml
plugins/uprecords/lang/ru.xml

Added and translated documentation file in Russian!

Added and translated documentation file in Russian!

---

plugins/smart/smart_bootstrap.html
templates/html/index_bootstrap.html
templates/phpsysinfo_bootstrap.css

Adding a div with class responsive-table (see; http://www.w3schools.com/bootstrap/bootstrap_ref_css_tables.asp) will work better, layout wise, for mobile browsers using the bootstrap theme.

Add reponsive table div

---

includes/output/class.Webpage.inc.php

fix for DEFAULT_BOOTSTRAP_TEMPLATE ini parameter 

---

language/ko.xml

Updated Korean translations

---

language/uk.xml

just fixed some grammatical issues and added few localized strings

Ukrainian locale fixes

---

language/uk.xml
plugins/ps/lang/uk.xml
plugins/psstatus/lang/uk.xml

just subj, with some spelling fixes.

Ukrainian locale update

---

.travis.yml

Current script is pretty fun, but it really doesnt do anything because dont return any exit codes on syntax or parsing errors.

Travis lint script updated

---

plugins/bat/lang/gr.xml

Greek language for bat plugin

---

language/zh.xml

Hello,
I translate some words into Chinese.

Translate some words into Chinese

---

language/id.xml

Translations: Add Indonesian Language

---

language/fa.xml

Hello,
I just added Persian translation files. In ISO 639-1 "fa" is stand for Persian language.
Also it's nice if we make right to left style for languages those are RTL just like Persian, Arabic and ect.

Persian (Farsi) language added.

---

language/ko.xml

Translate untranslated strings, edit existing translations to be more natural

Update Korean translations

---

read_config.php

http://php.watch/versions/8.0/disable_functions-redeclare

Fix php v8.0 bug - disable_functions behave as if they do not exist

---

language/fa.xml

Translate new Items

---

includes/os/class.Linux.inc.php

inet addr6

---

data/distros.ini
sample/distrotest/CentOS/Stream-8.txt

CentOS Stream

---

includes/class.CommonFunctions.inc.php

$strArguments

---

includes/class.CommonFunctions.inc.php

$strProgramname.' '.$strArguments

---

sample/main/dfk.txt

Darwin 'df -k' sample

---

includes/class.CommonFunctions.inc.php

PSI_ROOT_FILESYSTEM checking

---

includes/class.CommonFunctions.inc.php

log $strSet

---

includes/class.CommonFunctions.inc.php

check $strNewcmd

---

includes/class.CommonFunctions.inc.php

code optimization

---

includes/class.CommonFunctions.inc.php

find_program("sudo") info

---

data/ModelTranslation.txt

Fix incorrect model description. See https://everymac.com/ultimate-mac-lookup.

Mac 14,8 is a Mac Pro not a MacBook Pro
